name: Deploy to Cloudflare Workers

on:
  push:
    branches: [main]
    paths:
      - "index.js"
      - "wrangler.toml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Publish
        uses: cloudflare/wrangler-action@1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
